### PR TITLE
Bump up ethereum-ibc-relay-chain to v0.3.4

### PR DESCRIPTION
**Pull request by siburu**

### CODE REVIEW

**Review by bluele — APPROVED** [review]
@siburu LGTM 🚀

**Comment by bluele** [comment]
@siburu Could you update the module versions in the README?

**Comment by siburu** [comment]
> @siburu Could you update the module versions in the README before merging this?

@bluele Done!

**Review by bluele — APPROVED** [review]
@siburu LGTM 👍

**Pull request merged**
